# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.1.230309a1.dev56+gdc03526.d20230921'  # type: str
__version_tuple__ = version_tuple = (0, 1, 1, 230309, 'dev56', 'gdc03526.d20230921')  # type: tuple[int | str, ...]
